/* autogenerated by Processing revision 1310 on 2026-01-12 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class seagullGame extends PApplet {

/*
¡Hola, profesor Guillermo!:

Me emociona presentarle la entrega final de la materia, porque estoy bastante orgullosa del resultado. Aunque ciertamente el código podría haber quedado más sintetizado, por falta de tiempo hago
la entrega como está, aunque si es verdad que me esforcé para dejarlo lo más limpio posible.

Este juego está basado en el famoso Flappy Bird, pero inspirado en Vigo, la ciudad en la que vivo. La mecánica del juego consta en ir esquivando obtáculos, mientras recolectas artículos (comida) para
acumular puntos, y así para pasar de nivel. En total, el juego tiene tres niveles, en los que la velocidad de movimiento aumenta ligeramente respecto a la velocidad del nivel anterior, aumentando así
la dificultad. 

Para poder centrarme en la lógica del juego, utilicé recursos de imagen de estilo pixel-art de otros autores, posteriormente editados por mí, con el software Aseprite o con Photoshop. 
A continuación hago un listado de las referencias de imagen:

- Animación de gaviota: https://www.deviantart.com/spiritbeard/art/Pixel-Art-Seagull-Flying-Animation-1061933721 (utilicé dos de los 5 frames que componen la animación)
- Ciudad de fondo: https://www.freepik.com/free-vector/panorama-city-skyscrapers-sky-background-day-night_11332504.htm#fromView=search&page=2&position=29&uuid=f9649f76-6d28-42a0-a451-e436ad0acdef&query=european+city+pixel+art
- Chile: https://www.vecteezy.com/vector-art/23685234-pixel-art-chilli-hot-chilli-insect-pixelated-design-for-logo-web-mobile-app-badges-and-patches-video-game-sprite-8-bit-isolated-vector-illustration?autodl_token=a82ecd83c469e2ea5dee8a42cadefbf350084b97a522515891205605a0d4cac09abe228f04163dc173ccb6b369aa0e1ce6fec07c52905be8fd7f770e371fca9d
- Iconos comida: https://www.freepik.es/vector-gratis/iconos-comida-rapida-pixel-art_29012364.htm#fromView=search&page=1&position=1&uuid=fdf47428-5cd2-497f-b1e9-7f7dc7b009c5&query=fast+food+pixelart

Los postes y luces de navidad son de autoría propia. En el propio código incluyo las referencias de la música y efectos de sonido utilizados en el juego.

En relación al contenido que sirvió de ayuda para la realización del juego, dejo los enlaces a continuación:
- Coding Challenge #31: Flappy Bird - The Coding Train : https://www.youtube.com/watch?v=cXgA1d_E-jY&t=7s
- Adding Sounds to a Processing Project - John McCaffrey : https://www.youtube.com/watch?v=z9u9QRN4vgk

El programa tiene un pequeño menú con instrucciones, así que no es necesario explicarlas aquí :)

Espero que la entrega esté a la altura, y sobre todo que lo disfrute.

Un saludo,
Sarah
*/



//Imágenes a utilizar en el juego
PImage backgroundOne, backgroundTwo, backgroundDay, backgroundAfternoon, backgroundNight, seagullFlyingUp, seagullFlyingDown, 
shortLightsDay, shortLightsNight, longLightsDay, longLightsNight, pole, fries, doughnut, pizza, bocata, chili, heart0, heart1, heart2, jugarButton, instruccionesButton, salirButton, 
volverAJugarButton, menuButton, nextButton, prevButton, title, gameOverTitle, wonTitle, instructionsBase, instructions1, instructions2, instructions3, level1, level2, level3;
PFont f; //Fuente a utilizar en el juego
float backgroundOneXPos, backgroundTwoXPos, bgWidth; //Posiciones en X de la imagen duplicada de los fondos
float xMovementVelocity; //Controla la velocidad del movimiento del fondo y los elementos del juego (luces, postes e iconos de comida)
Seagull seagull; //Objeto del personaje, la gaviota
ArrayList<Light> lights = new ArrayList<Light>(); //Lista de instancias para las luces
ArrayList<Food> foods = new ArrayList<Food>(); //Lista de instancias para los iconos de comida
ArrayList<Button> mainMenuButtons = new ArrayList<Button>(); //Lista de instancias para los botones del menu principal
ArrayList<Button> gameOverButtons = new ArrayList<Button>(); //Lista de instancias para los botones del menu game over
ArrayList<Button> instructionsButtons = new ArrayList<Button>(); //Lista de instancias para los botones del menu de instrucciones
ArrayList<Confetti> confetti = new ArrayList<Confetti>(); //Lista de instancias para el confetti de la pantalla de ganar
//Posiciones para las luces, para los iconos de comida, vidas, posición de los iconos de vida en X
int[] lightsXPos, lightsYPos, foodsXPos, foodsYPos, lives, livesXPos;
int livesYPos; //Posición de iconos de vida en Y
int points, nextLevelMark, level;//Puntos acumulados, puntos necesarios para subir de nivel y conocer el nivel actual
float levelUpTime; //Almacenar el momento en el que sube de nivel
//Listas para la generación de luces e iconos de comida, utilizadas en sus respectivas listas de instancias. También para los iconos de las vidas
PImage[] everyFood, hearts, levelMessages;
boolean gameOver, gamePaused; //Para detectar cuándo se acaban las vidas o cuando se debe detener la velocidad
boolean showLevelMessage = false; //variable para activar o desactivar la animación del mensaje de aviso de nivel
float levelMessageXPos; //Variable para el posicionamiento de el rectángulo de fondo del anuncio en la función currentLevelMessage()
int menu, instructionsPage; //Para manejar la navegación entre menús
 //Usamos la librería Sound de Processing
SoundFile menuMusic, gameMusic, gameOverSfx, winningSfx, levelMessage, buttonOver, buttonClick, damage, nom1, nom2;
SoundFile[] nomSounds;
float rate; //Para la velocidad de la música según el nivel en el que estemos
boolean soundPlayed, levelSoundPlayed, menuMusicStarted, gameMusicStarted; //Para controlar la activación de sonidos


//SETUP ------------------------------------------------
public void setup(){
  /* size commented out by preprocessor */;
  
  //"Importamos" la fuente
  f = createFont("PixelifySans-VariableFont_wght.ttf", 128);
  
  //"Importamos" las imágenes utilizadas en le programa
  backgroundDay = loadImage("fondo.png");
  backgroundAfternoon = loadImage("fondoTarde.png");
  backgroundNight = loadImage("fondoNoche.png");
  seagullFlyingUp = loadImage("gaviotaVolando.png");
  seagullFlyingDown = loadImage("gaviotaCayendo.png");
  shortLightsDay = loadImage("luzCortaDia.png");
  shortLightsNight = loadImage("luzCortaNoche.png");
  longLightsDay = loadImage("luzLargaDia.png");
  longLightsNight = loadImage("luzLargaNoche.png");
  pole = loadImage("pole.png");
  fries = loadImage("patatas.png");
  doughnut = loadImage("rosquilla.png");
  pizza = loadImage("pizza.png");
  bocata = loadImage("bocata.png");
  chili = loadImage("chile.png");
  heart0 = loadImage("heart0.png");
  heart1 = loadImage("heart1.png");
  heart2 = loadImage("heart2.png");
  jugarButton = loadImage("jugarButton.png");
  volverAJugarButton = loadImage("volverAJugarButton.png");
  instruccionesButton = loadImage("instruccionesButton.png");
  salirButton = loadImage("salirButton.png");
  menuButton = loadImage("menuButton.png");
  nextButton = loadImage("nextButton.png");
  prevButton = loadImage("prevButton.png");
  title = loadImage("title.png");
  gameOverTitle = loadImage("gameOverTitle.png");
  wonTitle = loadImage("wonTitle.png");
  instructionsBase = loadImage("instrucciones.png");
  instructions1 = loadImage("info1.png");
  instructions2 = loadImage("info2.png");
  instructions3 = loadImage("info3.png");
  level1 = loadImage("nivel1.png");
  level2 = loadImage("nivel2.png");
  level3 = loadImage("nivel3.png");
  
  //Música y efectos de sonido
  menuMusic = new SoundFile(this, "menuMusic.wav"); //Game Music 140 BMP - Darren Hirst - https://pixabay.com/sound-effects/gamer-music-140-bpm-355954/
  gameMusic = new SoundFile(this, "gameMusic.wav"); // Electonic Fantasy - Patrick De Arteaga - https://patrickdearteaga.com/musica-libre-derechos-gratis/
  levelMessage = new SoundFile(this, "levelMessage.wav"); // Classic Game Action Positive 5 - floraphonic - https://pixabay.com/sound-effects/classic-game-action-positive-5-224402/
  gameOverSfx = new SoundFile(this, "gameOver.wav"); // Videogame Death Sound - Fupicat - https://pixabay.com/sound-effects/videogame-death-sound-43894/
  winningSfx = new SoundFile(this, "won.wav"); //WinSquare - Fupicat - https://pixabay.com/sound-effects/winsquare-6993/
  damage = new SoundFile(this, "damage.wav"); //Retro video game sfx - Bird chirp 2 by OwlStorm -- https://freesound.org/s/404727/ -- License: Creative Commons 0
  buttonOver = new SoundFile(this, "buttonOver.wav"); //Button UI Sound Effect - Emilianodleon - https://pixabay.com/sound-effects/button-ui-sound-effect-395762/
  buttonClick = new SoundFile(this, "buttonClick.wav"); //Select Button UI - Emilianodleon - https://pixabay.com/sound-effects/select-button-ui-395763/
  nom1 = new SoundFile(this, "nom1.wav"); //Nom_C_01.wav by PaulMorek -- https://freesound.org/s/172137/ -- License: Creative Commons 0 (Modificado por mí en Audacity)
  nom2 = new SoundFile(this, "nom2.wav"); //Nom_C_02.wav by PaulMorek -- https://freesound.org/s/172136/ -- License: Creative Commons 0 (Modificado por mí en Audacity)
  
  nomSounds = new SoundFile[] {nom1, nom2};
  
  //Posiciones del fondo
  backgroundOneXPos = 0;
  backgroundTwoXPos = 1432;
  bgWidth = backgroundDay.width; //Las tres imagenes de fondo tienen el mismo ancho, así que apunto a cualquiera de ellas
  
  //Inicializamos los arrays de posiciones para elementos como luces, comida y posición de los iconos de vida
  lightsXPos = new int[] {676, 1102, 1520, 1980, 2405, 2674, 3058, 3300, 3650, 4002};
  lightsYPos = new int[] {418, 266, 406, 188, 412, 311, 231, 400, 370, 194};

  foodsXPos = new int[] {707, 1159, 1547, 1965, 2073, 2326, 2732, 3059, 3121, 3364, 3655, 3954};
  foodsYPos = new int[] {603, 100, 602, 97, 106, 599, 602, 106, 50, 606, 300, 556};
  
  livesXPos = new int[] {1020, 1071, 1121};
  livesYPos = 32;
  
  //Nuestro array de vidas. Se hace en forma de array para poder manejar más facilmente  y de forma independiente los iconos
  lives = new int[] {2, 2, 2};
  
  //Array de imágenes de las vidas, para actualizar sus iconos facilmente junto con el array de vidas
  hearts = new PImage[]{
    heart0, // vacío
    heart1, // por la mitad
    heart2  // lleno
  };
  
  //Array de imágenes, utilizado para dar aleatoriedad a la asignación de imágenes de las instancia food
  everyFood = new PImage[]{
    fries,
    doughnut,
    pizza,
    bocata,
    chili,
    chili //Duplicamos para que hayan más probabilidades de que aparezca un chile
  };
  
  //Array de imágenes de mensajes de nivel
  levelMessages = new PImage[]{
    level1,
    level2,
    level3
  };
    
  //Agregamos a los arraylist de comida y luces sus respectivas instancias. La imagen será aleatoria y diferente cada vez que se inicie el programa.
  for(int i = 0; i < lightsXPos.length; i++){
    boolean shortLight = random(1) < 0.5f;
    PImage img = shortLight ? shortLightsDay : longLightsDay;
    lights.add(new Light(img, shortLight, lightsXPos[i], lightsYPos[i]));
  }
  
  for(int i = 0; i < foodsXPos.length; i++){
    foods.add(new Food(everyFood[PApplet.parseInt(random(0, everyFood.length))], foodsXPos[i], foodsYPos[i]));
  }
  
  //Agregamos instancias de confetti al arraylist
  for (int i = 0; i < 120; i++) {
    confetti.add(new Confetti());
  }
  
  //Agregamos a los arraylist las instancias de botones que deben aparecer en pantalla
  mainMenuButtons.add(new Button(jugarButton, width/2, 410, "play"));
  mainMenuButtons.add(new Button(instruccionesButton, width/2, 500, "instructions"));
  mainMenuButtons.add(new Button(salirButton, width/2, 590, "exit"));
  
  gameOverButtons.add(new Button(volverAJugarButton, width/2, 468, "play"));
  gameOverButtons.add(new Button(salirButton, width/2, 558, "exit"));
  
  instructionsButtons.add(new Button(menuButton, width/2, 630, "menu"));
  instructionsButtons.add(new Button(prevButton, width/2 - 200, 635, "back"));
  instructionsButtons.add(new Button(nextButton, width/2 + 200, 635, "next"));
  
  //Creamos el objeto seagull para nuestro personaje
  seagull = new Seagull(seagullFlyingUp, 100, height/2);
  
  //Inicializamos los valores de varaibles de juego
  points = 0;
  level = 1;
  nextLevelMark = 20;
  gameOver = false;
  gamePaused = false;
  menu = 0;
  rate = 1.0f;
  soundPlayed = false;
  levelSoundPlayed = false;
  menuMusicStarted = false;
  gameMusicStarted = false;
  
}

//DRAW ----------------------------------------
public void draw(){
  
  //Controla la música de las pantallas de menu (desde aquí para no sobre cargar el programa por el uso de loop())
  if(menu == 0 || menu == 2){
    playMenuMusic();
    menuMusicStarted = true;
  }
  
  //Para poder cambiar entre pantallas
  switch(menu){
    
    //MENÚ PRINCIPAL
    case 0:
      mainMenu();
    break;
    
    //JUEGO
    case 1:
    if(!gameOver){
            
    if(menuMusic.isPlaying()){
      menuMusic.pause();
      menuMusicStarted = false;
    }
    
    gameMusic.rate(rate);
    
    if(!gameMusicStarted){
      gameMusic.loop();
      gameMusicStarted = true;
    }
              
    levelUp();
    
    //Cambiamos el fondo y la velocidad de acuerdo con el nivel en el que estemos
    switch(level){
      case 1:
        xMovementVelocity = gamePaused ? 0 : 6; //Modificar para mayor o menor velocidad de juego. Si el juego está pausado la velocidad es 0
        nextLevelMark = 20;
        backgroundOne = backgroundDay;
        backgroundTwo = backgroundDay;
        image(backgroundOne, backgroundOneXPos, -100);
        image(backgroundTwo, backgroundTwoXPos, -100);
        break;
      case 2:
        xMovementVelocity = gamePaused ? 0 : 8;
        nextLevelMark = 15;
        backgroundOne = backgroundAfternoon;
        backgroundTwo = backgroundAfternoon;
        image(backgroundOne, backgroundOneXPos, -100);
        image(backgroundTwo, backgroundTwoXPos, -100);
        break;
      case 3:
        xMovementVelocity = gamePaused ? 0 : 10;
        nextLevelMark = 10;
        backgroundOne = backgroundNight;
        backgroundTwo = backgroundNight;
        image(backgroundOne, backgroundOneXPos, -100);
        image(backgroundTwo, backgroundTwoXPos, -100);
        for(Light light : lights){
          light.turnOn();
        }
        break;
    }
    
    isGameOver();
    
    seagull.display();
       
    if(!gamePaused){
      seagull.gravityBehaviour();
    }
    
    //Movimiento horizontal de las imágenes, a mayor valor, mayor velocidad
    backgroundOneXPos -= xMovementVelocity;
    backgroundTwoXPos -= xMovementVelocity;
    
    //Permite posicionar los fondos uno después del otro, para dar sensación de movimiento con la repetición de la imagen
    if(backgroundOneXPos <= - bgWidth){
      backgroundOneXPos = backgroundTwoXPos + bgWidth;
    }  
    if(backgroundTwoXPos <= - bgWidth){
      backgroundTwoXPos = backgroundOneXPos + bgWidth;
    }

    for(Food food : foods){
      food.display();
      food.move();
      food.updateIcon();
      food.reactivateFood();
      
      float fx = food.imageXPos + food.image.width / 2 + 5; //Ancho
      float fy = food.imageYPos + food.image.height / 2; //Alto
      float frX = (food.image.width + 10) / 2; //Radio X
      float frY = (food.image.height + 10) / 2; //Radio Y
      
      if(collides(seagull, fx, fy, frX, frY)){
        food.collisionBehaviour();
      }
    }
    
    for(Light light : lights){
      light.display();
      light.drawPole();
      light.move();
      light.cooldownBehaviour();
      
      float ox = light.imageXPos + light.image.width / 2 - 10; //Ancho
      float oy = light.imageYPos + light.image.height / 2; //Alto
      float orX = (light.image.width + 10) / 2; //Radio X
      float orY = (light.image.height + 10) / 2; //Radio Y
      
      if(collides(seagull, ox, oy, orX, orY)){
        light.collisionBehaviour();
      }
    }
    
    if (showLevelMessage) {
      currentLevelMessage();
    }
    
    adjustLightsPos();
    adjustFoodPos();
    drawLives();
    printPoints();
  }

  break;
  
  //INSTRUCCIONES
  case 2:
    instructionsMenu();
  break;
  
  //PERDER - GAME OVER
  case 3:
    gameOverMenu();
  break;
  
  //GANAR
  case 4:
    wonMenu();
  break;
  
  }
  
  
}

//FUNCIONES ADICIONALES --------------------------------------------------------

//REAJUSTE DE POSICIÓNES DE LUCES Y COMIDA PARA MOVIMIENTO INFINITO

//Reajustar la posición en X de las instancias de las luces de navidad y hacer el efecto de movimiento infinito junto con el fondo
public void adjustLightsPos(){
    
    float maxXPos = -Float.MAX_VALUE;
    
    for(Light l : lights){
      if(l.imageXPos > maxXPos){
        maxXPos = l.imageXPos;
      }
    }
    
    for(Light l : lights){
      if(l.imageXPos + l.image.width < 0){
        l.imageXPos = maxXPos + l.image.width + 200;
      }
    }
}

//Reajustar la posición de la comida para dar la apariencia de que se generan infinitamente
public void adjustFoodPos(){
  
  float maxXPos = -Float.MAX_VALUE;
  
  for(Food food : foods){
    if(food.imageXPos > maxXPos){
      maxXPos = food.imageXPos;
    }
  }
  
  for(Food food : foods){
    if(food.imageXPos + food.image.width < 0){
      food.imageXPos = maxXPos + food.image.width + 260;
    }
  }
  
}

//CONTROLES PERSONAJE
public void keyPressed(){
  if(!gamePaused){
    switch(keyCode){
    case UP:
    seagull.moveUp();    
    break;
    
    case DOWN:
    seagull.isDiving = true;
    seagull.moveDown();
    break;
    
    case LEFT:
    seagull.moveLeft();
    break;
    
    case RIGHT:
    seagull.moveRight();
    break;
    }
  }
}

public void keyReleased(){
  if(!gamePaused){
    if(keyCode == DOWN){
      seagull.isDiving = false;
    }
  }
}

//PUNTUACIÓN, VIDAS Y COLISIONES --------------

//Imprimir iconos de vida
public void drawLives(){
  for(int i = 0; i < lives.length; i++){
    image(hearts[lives[i]], livesXPos[i], livesYPos);
  }
}

//Imprimir puntuación
public void printPoints(){
  if(level == 3){
    fill(255);
  } else {
    fill(0);
  }
  textFont(f);
  textSize(31);
  text("Puntos: " + points, 20, livesYPos + 20);
}

//Restar una vida
public void subtractALife(Seagull s){
  
  for(int i = 0; i < lives.length; i++){
    if(lives[i] > 0){
      lives[i] -=1;
      if(!soundPlayed){
        damage.play();
      }
      break;
    }
  }
  
  soundPlayed = false;
  
  //Animación gaviota
  s.isDamaged = true;
  s.damageTime = millis();
  
}

//Colisiones, además del objeto Seagull, pasaremos la posición en X o Y de cualquier objeto al que se desee aplicar la colisión, así como el radio X y Y de una elipse que bordee dicho objeto
public boolean collides(Seagull s, float ox, float oy, float orX, float orY){
  
  //Variables locales gaviota
  int w = s.isDiving ? s.diveW : s.flyW; //Ancho
  int h = s.isDiving ? s.diveH : s.flyH; //Alto

  float sx = s.imageXPos + w / 2; //Posición X
  float sy = s.imageYPos + h / 2; //Posición Y
  float srX = w * 0.45f; //Radio X
  float srY = h * 0.4f; //Radio Y

  //Variables locales para calcular las distancias entre la elipse de la gaviota y la de una instancia a la que se aplique la función
  float dx = sx - ox; //Distancia en X
  float dy = sy - oy; //Distancia en Y

  //Normalización de las distancias de ambas elipses
  float nx = dx / (srX + orX);
  float ny = dy / (srY + orY);

  //Comprobar si las áreas de ambas elipses están dentro de un círculo unitario, la ecuación es x^2 + y^2 <= 1
  return (nx * nx + ny * ny) <= 1;
}

//LÓGICA GAME OVER --------------
public void isGameOver(){
  int sum = 0;
  for(int i = 0; i < lives.length; i++){
    sum += lives[i];
  }
  if(sum < 1){
    gameOver = true;
    menu = 3; //Si se pierde, se pasa a la pantalla correspondiente
    gameMusic.pause();
    gameMusicStarted = false;
  }
}

//LÓGICA NIVELES Y PUNTOS --------------

//Subir de nivel
public float levelUp(){
  if(points >= nextLevelMark && level < 3){
    level += 1;
    rate += 0.01f;
    points -= nextLevelMark;
    startLevelMessage();
  } else if (level == 3 && points >= nextLevelMark){
    menu = 4; //Si se gana, se pasa a la pantalla correspondiente
    gameMusic.pause();
    gameMusicStarted = false;
  }
  return levelUpTime;
}

//Función a utilizar en currentLevelMessage y comportamiento del botón tipo play
public void startLevelMessage() {
  levelUpTime = millis();
  showLevelMessage = true;  //Activamos la animación del mensaje de nivel
  gamePaused = true; //Pausamos el juego
}

////Mensaje de subida de nivel, muestra un bloque de animación que entra en la pantalla en medio segunda, se queda un segundo, y sale de la pantalla en medio segundo
public void currentLevelMessage(){

  float slideTime = 500;   // ms
  float pauseTime = 1000;  // ms
  float totalTime = slideTime * 2 + pauseTime;
  float elapsed = millis() - levelUpTime;
  
  if(elapsed > totalTime) {
    showLevelMessage = false;
    gamePaused = false;
    levelSoundPlayed = false;
    return;
  }
  
  if(elapsed < slideTime){
    float t = elapsed / slideTime;
    levelMessageXPos = lerp(-width, 0, t);

  } else if(elapsed < slideTime + pauseTime){
    levelMessageXPos = 0;

  } else {
    float t = (elapsed - slideTime - pauseTime) / slideTime;
    levelMessageXPos = lerp(0, width, t);
  }

  //Dibujar el mensaje en pantalla
  fill(255, 120);
  noStroke();
  rect(levelMessageXPos, 0, width, height);
  image(levelMessages[level-1], levelMessageXPos + width*1.5f/4, height/2);
  if(!levelSoundPlayed){
    levelMessage.play();
    levelSoundPlayed = true;
  }

  
}


//Resetear juego
public void resetGame(){
  
  //Puntuación y vidas
  points = 0;
  level = 1;
  gameOver = false;
  gamePaused = false;
  lives = new int[]{2, 2, 2};
  soundPlayed = false;
  rate = 1.0f;
  
  //Fondo y velocidad general
  backgroundOneXPos = 0;
  backgroundTwoXPos = bgWidth;
  
  //Gaviota
  seagull.imageXPos = 100;
  seagull.imageYPos = height/2;
  seagull.targetX = seagull.imageXPos;
  seagull.targetY = seagull.imageYPos;
  seagull.isDiving = false;
  seagull.isDamaged = false;
  
  //Postes de luz
  for(int i = 0; i < lights.size(); i++){
    Light l = lights.get(i);
    l.imageXPos = lightsXPos[i];
    l.imageYPos = lightsYPos[i];
    l.active = true;
    l.deactivationTime = 0;
    l.turnOff();
  }
  
  //Comida
  for(int i = 0; i < foods.size(); i++){
    Food f = foods.get(i);
    f.imageXPos = foodsXPos[i];
    f.imageYPos = foodsYPos[i];
    f.active = true;
    f.deactivationTime = 0;
  }
  
  // Reset animación de mensaje de nivel
  showLevelMessage = false;
  levelMessageXPos = -width;
  levelUpTime = 0;
  levelSoundPlayed = false;

}


//PANTALLAS DE MENÚ --------------------------

public void base(){
  pushStyle();
  image(backgroundDay, -75, -100);
  fill(255, 180);
  rectMode(CORNER);
  rect(0, 0, width, height);
  popStyle();
}

//Menú principal
public void mainMenu(){
  base();
  image(title, 347, 70);
  
  //Dibujamos todos los botones de la pantalla principal
  for(Button button : mainMenuButtons){
    pushStyle();
    imageMode(CENTER);
    button.display();
    popStyle();
  }
  
}

//Menú instrucciones
public void instructionsMenu(){
  gamePaused = true;
  base();
  image(instructionsBase, 78, 78);
  switch(instructionsPage){
    case 1:
      image(instructions1, 111, 191);
      for(Button button : instructionsButtons){
        if(button.function != "back"){
          pushStyle();
          imageMode(CENTER);
          button.display();
          popStyle();
        }
      }
    break;
    case 2:
      image(instructions2, 111, 191);
      for(Button button : instructionsButtons){
        pushStyle();
        imageMode(CENTER);
        button.display();
        popStyle();
      }
    break;
    case 3:
      image(instructions3, 111, 191);
      for(Button button : instructionsButtons){
        if(button.function != "next"){
          pushStyle();
          imageMode(CENTER);
          button.display();
          popStyle();
        }
      }
    break;
  }
  
}



//Perder
public void gameOverMenu(){
  base();
  image(gameOverTitle, 318, 204);
  
  for(Button button : gameOverButtons){
    pushStyle();
    imageMode(CENTER);
    button.display();
    popStyle();
  }
  
  gamePaused = true;
  
  if(!soundPlayed){
    menuMusic.pause(); //Para evitar la superposición con el sonido de game over
    gameOverSfx.play();
    soundPlayed = true;
  }
}

//Ganar
public void wonMenu(){
  base();
  image(wonTitle, 318, 204);
  
  for(Button button : gameOverButtons){
    pushStyle();
    imageMode(CENTER);
    button.display();
    popStyle();
  }
  
  for (Confetti c : confetti) {
    c.update();
    c.display();
  }

  gamePaused = true;
  
  if(!soundPlayed){
    menuMusic.pause(); //Para evitar la superposición con el sonido de victoria
    winningSfx.play();
    soundPlayed = true;
  }
}

//Función para controlar la música de las pantallas de los menús Principal, Perder, Ganar e Instrucciones
public void playMenuMusic(){
  if(!menuMusicStarted){
    if(gameMusic.isPlaying()){
      gameMusic.pause();
      gameMusicStarted = false;      
    }
    menuMusic.loop();
    menuMusicStarted = true;
  }
}

//ACCIÓN DE LOS BOTONES ------------------------
public void mouseClicked(){

  // MENÚ PRINCIPAL
  if(menu == 0){
    for(Button button : mainMenuButtons){
      if(button.mouseOver()){
        
        if(buttonClick.isPlaying() == false ){
          buttonClick.play();
        }
        
        switch(button.function){
          case "play":
            menu = 1;
            resetGame();
            startLevelMessage();
            break;

          case "exit":
            exit();
            break;
            
          case "instructions":
            menu = 2;
            instructionsPage = 1;
          break;
        }
      }
    }
  }
  
  //INSTRUCCIONES
  else if(menu == 2){
    for(Button button : instructionsButtons){
      if(button.mouseOver()){
        
        if(buttonClick.isPlaying() == false ){
          buttonClick.play();
        }
        
        switch(button.function){
          case "menu":
            menu = 0;
            break;

          case "back":
          if(instructionsPage > 1){
            instructionsPage -= 1;
          }
          break;
          
          case "next":
          if(instructionsPage < 3){
            instructionsPage += 1;
          }
          break;
        }
      }
    }
  }

  //PANTALLA GAME OVER O WON
  else if(menu == 3 || menu == 4){
    for(Button button : gameOverButtons){
      if(button.mouseOver()){
        
        if(buttonClick.isPlaying() == false ){
          buttonClick.play();
        }
        
        switch(button.function){
          case "play":
            menu = 1;
            resetGame();
            startLevelMessage();
            break;

          case "exit":
            exit();
          break;
        }
      }
    }
  }
}
class Button{
  PImage image;
  float xPos, yPos;
  int imgWidth, imgHeight;
  String function; //función del botón
  boolean wasHovered = false; //Para controlar sonidos
  
  Button(PImage _image, float _xPos, float _yPos, String _function){
    image = _image;
    xPos = _xPos;
    yPos = _yPos;
    function = _function;
    imgWidth = image.width;
    imgHeight = image.height;
  }
  
  public void display(){
    if(mouseOver()){
      image(image, xPos, yPos, imgWidth + 5, imgHeight + 2);
      if(!wasHovered){
        buttonOver.play();
      }
    } else {
      image(image, xPos, yPos, imgWidth, imgHeight);
    } 
    wasHovered = mouseOver();
  }
  
  //Método para comprobar si el cursor está sobre el botón
  public boolean mouseOver(){
    float halfW = imgWidth / 2;
    float halfH = imgHeight / 2;
    boolean xArea = mouseX >= xPos - halfW && mouseX <= xPos + halfW;
    boolean yArea = mouseY >= yPos - halfH && mouseY <= yPos + halfH;
    return xArea && yArea;
  }

}
//Clase Confettti para la pantalla de juego ganado
class Confetti {
  float x, y;
  float speedY;
  float speedX;
  float size;
  float angle;
  float rotationSpeed;
  int col;

  Confetti() {
    reset();
    y = random(-height, 0);
  }

  public void reset() {
    x = random(width);
    y = random(-100, -10);
    speedY = random(2, 6);
    speedX = random(-1.5f, 1.5f);
    size = random(6, 12);
    angle = random(TWO_PI);
    rotationSpeed = random(-0.1f, 0.1f);
    col = color(random(255), random(255), random(255));
  }

  public void update() {
    y += speedY;
    x += speedX;
    angle += rotationSpeed;

    if (y > height + 20) {
      reset();
    }
  }

  public void display() {
    pushMatrix();
    translate(x, y);
    rotate(angle);
    noStroke();
    fill(col);
    rectMode(CENTER);
    rect(0, 0, size, size * 0.6f);
    popMatrix();
  }
}
class Food {
PImage image;
float imageXPos;
float imageYPos;
boolean poisonous;
boolean active = true; //Controlamos si la comida ha sido tocada por la gaviota o no
int timeToRespawn = 5000; // Tiempo en milisegundos para que la comida vuelva a aparecer después de comerla
float deactivationTime; //Controla cuánto tiempo ha pasado desde que se "comió" un alimento

//Alto y ancho de cada imagen (tienen altos y anchos diferentes para mantener la proporción)
int friesW = 51;
int friesH = 62;
int doughnutW = 85;
int doughnutH = 52;
int pizzaW = 56;
int pizzaH = 62;
int bocataW = 70;
int bocataH = 62;
int chiliW = 32;
int chiliH = 81;

Food(PImage _image, float _imageXPos, float _imageYPos){
  image = _image;
  imageXPos = _imageXPos;
  imageYPos = _imageYPos;
  poisonous = (image == chili); //Si la imagen es un chile, poisonous será true
}

public void display(){
  if(active){
    if(image == fries){
      image(image, imageXPos, imageYPos, friesW, friesH);
    } else if (image == doughnut){
      image(image, imageXPos, imageYPos, doughnutW, doughnutH);
    } else if (image == pizza){
      image(image, imageXPos, imageYPos, pizzaW, pizzaH);
    } else if (image == bocata){
      image(image, imageXPos, imageYPos, bocataW, bocataH);
    } else {
      image(image, imageXPos, imageYPos, chiliW, chiliH);
    }
  }
}

//Método para movimiento
public void move(){
  imageXPos -= xMovementVelocity;
}

//Cambiar el icono por otro cuando sale de pantalla para no repetir la secuencia generada en setup()
public void updateIcon(){
  if(imageXPos + image.width < 0){
    image = everyFood[PApplet.parseInt(random(0, everyFood.length))];
    imageXPos -= image.width;
    if(image == chili){
      poisonous = true;   
    } else {
      poisonous = false;
    }
  }
}

//Comportamiento de suma puntos y resta de vidas
public void collisionBehaviour(){
  if(active){
    if(poisonous){
      subtractALife(seagull);
    } else {
      points += 1;
      if(!soundPlayed){
        int randomSfx = PApplet.parseInt(random(0, 2));
        nomSounds[randomSfx].play();
        soundPlayed = true;
      }
    }
  }
  active = false;
  deactivationTime = millis();
  soundPlayed = false;
}

//Hace que la comida reaparezca después de haberla "comido"
public void reactivateFood(){
  if(!active && millis() - deactivationTime >= timeToRespawn){
    active = true;
  }
}

}
class Light {
PImage image;
float imageXPos;
float imageYPos;
boolean active, isShort; //Active determina si la gaviota ha chocado con la luz o no, para manejar enfriamiento y resta de vidas. isShort será utilizada para almacenar el tipo de imagen (luz corta o larga) y poderla actualizar en el nivel 3
int cooldownTime = 3000; // Tiempo en milisegundos para que una luz vuelva a hacer daño
float deactivationTime; //Controla cuánto tiempo ha pasado desde que la gaviota chocó contra una luz

Light(PImage _image, boolean _isShort, float _imageXPos, float _imageYPos){
  image = _image;
  isShort = _isShort;
  imageXPos = _imageXPos;
  imageYPos = _imageYPos;
}
 
public void display(){
  image(image, imageXPos, imageYPos);
  noFill();
  stroke(0);
}

//Método para dibujar el poste después de la luz
public void drawPole(){
  image(pole, imageXPos + image.width, imageYPos + 20);
}

//Método para que las luces se muevan junto con el fondo
public void move(){
  imageXPos -= xMovementVelocity;
}

public void collisionBehaviour(){
  if(active){
    subtractALife(seagull);
  }
  active = false;
  deactivationTime = millis();
}

public void cooldownBehaviour(){
  if(!active && millis() - deactivationTime >= cooldownTime){
    active = true;
  }
}

//Usar las imagenes de luces nocturnas
public void turnOn(){
  image = isShort ? shortLightsNight : longLightsNight;
}

//Usar las imagenes de luces diurnas
public void turnOff(){
  image = isShort ? shortLightsDay : longLightsDay;
}
  
}
class Seagull {
PImage image;
float imageXPos;
float imageYPos;
float targetX, targetY; //Para ubicar un nuevo punto al cual se moverá la gaviota, aportará suavidad visual al accionar los controles de movimiento con el uso de lerp()
//Variables para controlar la dimensión de la imagen de la gaviota según el movimiento
int flyW = 118;
int flyH = 34;
int diveW = 77;
int diveH = 48;
int velocity = 5; //Variable para controlar la velocidad del movimiento con los controles del juego
float gravity = 0.01f; //Magnitud de la gravedad que usaremos en el comportamiento de caída libre para la posición en Y
boolean isDiving = false; //Controlar la animación del vuelo hacia abajo
boolean isDamaged = false; //Controlar animación de daño cuando colisiona
float damageTime; //Para guardar el momento exacto en que colisiona contra un objeto que haga daño
int damageDuration = 1000; //En ms
float h = isDiving ? diveH : flyH;


Seagull(PImage _image, float _imageXPos, float _imageYPos){
  image = _image;
  imageXPos = _imageXPos;
  imageYPos = _imageYPos;
  targetX = imageXPos;
  targetY = imageYPos;
}

public void display(){
  pushStyle(); //Para aplicar estilos de imagen únicamente a la gaviota y no a otros elementos del sistema
  
  //Animaciones para cuando se recibe daño
  if(isDamaged){
    if(millis() / 100 % 2 == 0){ //Cuando millis() sea par, aplicamos el código de debajo, para un efecto de parpadeo
      tint(255, 0); //Opacidad del 0%
    } else {
    tint(255, 255);
    }
    
    if(millis() - damageTime > damageDuration){ //Apagamos la condición isDamaged después de un segundo
      isDamaged = false;
    }
  } else { //Si la condición isDamaged está apagada, la imagen se muestra sin transparencia
    tint(255, 255);
  }
  
  //Movimiento de la imagen
  if(!gamePaused){
    imageXPos = lerp(imageXPos, targetX, 0.12f);
    imageYPos = lerp(imageYPos, targetY, 0.12f);
  }

  //Animación de movimiento vertical, hacia arriba o hacia abajo
  if(isDiving){
    image(seagullFlyingDown, imageXPos, imageYPos, diveW, diveH);
  } else {
    image(seagullFlyingUp, imageXPos, imageYPos, flyW, flyH);
  }
  
  popStyle();
}

//SIMULACIÓN LEYES FÍSICAS
//Método que simula el movimiento en caída libre y la acción de la gravedad sobre la gaviota
public void gravityBehaviour(){
  if(targetY + h < height){ //Límite de posición dentro de la pantalla
    velocity += gravity;
    targetY += velocity;
  }
}

//CONTROLES DE MOVIMIENTO
public void moveUp(){
  if(imageYPos - image.height*3.6f/4 > 0){ //Para que la gaviota no se salga de la pantalla. Hacemos los mismos ajustes en los siguientes métodos para el control de movimiento
    targetY -= velocity*20;
  }
}

public void moveDown(){
  if(targetY + h < height){
    targetY += velocity*20;
  } else {
    targetY = height - h - h/2;
  }
}

public void moveLeft(){
  if(imageXPos - image.width/4 > 0){
    targetX -= velocity*20;
  } 
}

public void moveRight(){
  if(imageXPos + image.width < width){
    targetX += velocity*20;
  } 
}


}


  public void settings() { size(1200, 700, P2D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "seagullGame" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
